version: "3"
services:
  mysql_demo:
    container_name: mysql_demo
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "$PWD/mysql-data:/var/lib/mysql"
      #- "$PWD/conf/conf.d:/etc/nginx/conf.d"
      # - "$PWD/certs:/etc/nginx/certs"
      #- "$PWD/logs:/var/log/nginx"
